# fly.toml app configuration file generated for server-dry-darkness-2221 on 2025-02-15T21:51:24+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-dry-darkness-2221'
primary_region = 'bom'

[build]



[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
